# docker-compose.yml - Composition of micro-services to run OpenDLV software.
# Copyright (C) 2016 Christian Berger
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.

# Date: 2016-09-09

version: '2'

services:
    odsupercomponent:
        build: .
        network_mode: "host"
        volumes:
        - .:/opt/opendlv.data
        command: "/opt/od4/bin/odsupercomponent --cid=${CID} --verbose=1 --configuration=/opt/opendlv.data/configuration"

    # micro service for proxy-lidar
    proxy-lidar:
        build: .
        network_mode: "host"
        ipc: host
        user: root  # This parameter will be replaced as soon as group_add parameter is available in docker-compose, cf. https://github.com/docker/compose/pull/3709.
        volumes:
        - .:/opt/opendlv.data
        adevices:
             - "/dev/ttyS1:/dev/ttyS1"
        depends_on:
            - odsupercomponent
        command: "/opt/opendlv.core/bin/opendlv-core-system-proxy-sick --cid=${CID} --freq=1"

    # odcockpit:
    #     build: .
    #     network_mode: "host"
    #     environment:
    #     - DISPLAY=$DISPLAY
    #     volumes:
    #     - /tmp/.X11-unix:/tmp/.X11-unix
    #     # - ~/recordings:/opt/recordings
    #     - .:/opt/opendlv.data
    #     ipc: host
    #     user: odv
    #     depends_on:
    #         - odsupercomponent
    #     command: "/opt/od4/bin/odcockpit --cid=${CID}"
        

        
